name: Release from tag

on:
  push:
    tags:
      - '*' # SemVer version, e.g. 1.2.3

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
              
    - name: Build & pack
      id: build_pack
      run: dotnet build --configuration Release /p:Version=${{ github.ref_name }}

    - name: Upload package
      uses: actions/upload-artifact@v2
      with:
        name: package
        path: ClickHouse.Client/bin/Release/ClickHouse.Client.*nupkg

  push_github:
    runs-on: windows-latest
    needs: [build]    
    name: Upload to GitHub Packages
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: package

    - name: Push package
      id: push
      shell: cmd
      run: dotnet nuget push ClickHouse.Client.*.nupkg --skip-duplicate --api-key ${{ secrets.GITHUB_TOKEN }} --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json

  push_nuget_org:
    runs-on: windows-latest
    needs: [build]
    name: Upload to NuGet.org
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: package
      
    - name: Push package
      id: push
      shell: cmd
      run: dotnet nuget push ClickHouse.Client.*.nupkg --skip-duplicate --api-key ${{ secrets.NUGET_TOKEN }} --source https://api.nuget.org/v3/index.json

  github_release:
    runs-on: windows-latest
    needs: [build]
    name: Create GitHub release
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: package

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        prerelease: false
        generate_release_notes: true
        tag_name: ${{ github.ref_name }}
        name: ${{ github.ref_name }}
        files: |
          ClickHouse.Client.*.nupkg
          ClickHouse.Client.*.snupkg
