name: Release NuGet packages

on:
  push:
    tags:
      - '*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
              
    - name: Build & pack
      id: build_pack
      run: dotnet build --configuration Release /p:Version=${{ github.ref_name }}

    - name: Upload package
      uses: actions/upload-artifact@v2
      with:
        name: package
        path: ClickHouse.Client/bin/Release/ClickHouse.Client.*nupkg

  push_github:
    runs-on: windows-latest
    needs: [build]    
    name: Upload to GitHub Packages
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v2.1.0
      with:
        name: package

    - name: Setup NuGet
      id: setup
      uses: actions/setup-dotnet@v1
      with:
        source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Push package
      id: push
      run: dotnet nuget push ClickHouse.Client.nupkg

  push_nuget_org:
    runs-on: windows-latest
    needs: [build]
    name: Upload to NuGet.org
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v2.1.0
      with:
        name: package

    - name: Setup NuGet
      id: setup
      uses: actions/setup-dotnet@v1
      with:
        source-url: https://api.nuget.org/v3/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}

    - name: Push package
      id: push
      run: dotnet nuget push ClickHouse.Client.nupkg

  github_release:
    runs-on: windows-latest
    needs: [build, push_github, push_nuget_org]
    name: Create GitHub release
    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: ${{ github.ref_name }}
        body: |
          * **Added**: 
          * **Fixed**: 
          * **Improved**:
        draft: true
        prerelease: true
